version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: insider-nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nba:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm

  php-fpm:
    build: ./docker/php8
    container_name: insider-php-container
    links:
      - mysql
      - redis
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_HOST=mysql
      - DB_NAME=insider_nba
      - DB_USER=root
      - DB_PASS=
      - DB_PORT=3306

    volumes:
      - ./nba:/var/www

  redis:
    image: redis:4.0.5-alpine
    container_name: insider-redis-container
    ports:
      - 6379:6379
    hostname: redis
    volumes:
      - redis-data:/data

  mysql:
    image: mariadb:10.5.8
    container_name: insider-mysql-container
    ports:
      - 33060:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: insider_nba
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - my-data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    command: [ "--init-file", "/docker-entrypoint-initdb.d/database.sql" ]
volumes:
  redis-data:
  my-data:
