INSERT INTO `teams` (name,short_name,conference,team_group) VALUES
                          ('Atlanta Hawks','ATL','East','Southeast'),
                          ('Boston Celtics','BOS','East','Atlantic'),
                          ('Brooklyn Nets','BKN','East','Atlantic'),
                          ('Charlotte Hornets','CHA','East','Southeast'),
                          ('Chicago Bulls','CHI','East','Central'),
                          ('Cleveland Cavaliers','CLE','East','Central'),
                          ('Dallas Mavericks','DAL','West','Southwest'),
                          ('Denver Nuggets','DEN','West','Northwest'),
                          ('Detroit Pistons','DET','East','Central'),
                          ('Golden State Warriors','GSW','West','Pacific'),
                          ('Houston Rockets','HOU','West','Southwest'),
                          ('Indiana Pacers','IND','East','Central'),
                          ('LA Clippers','LAC','West','Pacific'),
                          ('LA Lakers','LAL','West','Pacific'),
                          ('Memphis Grizzlies','MEM','West','Southwest'),
                          ('Miami Heat','MIA','East','Southeast'),
                          ('Milwaukee Bucks','MIL','East','Central'),
                          ('Minnesota Timberwolves','MIN','West','Northwest'),
                          ('New Orleans Hornets','NOH','West','Southwest'),
                          ('New York Knicks','NYK','East','Atlantic'),
                          ('Oklahoma City Thunder','OKC','West','Northwest'),
                          ('Orlando Magic','ORL','East','Southeast'),
                          ('Philadelphia Sixers','PHI','East','Atlantic'),
                          ('Phoenix Suns','PHX','West','Pacific'),
                          ('Portland Trail Blazers','POR','West','Northwest'),
                          ('Sacramento Kings','SAC','West','Pacific'),
                          ('San Antonio Spurs','SAS','West','Southwest'),
                          ('Toronto Raptors','TOR','East','Atlantic'),
                          ('Utah Jazz','UTA','West','Northwest'),
                          ('Washington Wizards','WAS','East','Southeast');
